{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "PandasGUI ERROR — pandasgui.store — name 'sess' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 231, in resolve\n",
      "    return self.resolvers[key]\n",
      "           ~~~~~~~~~~~~~~^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\collections\\__init__.py\", line 1014, in __getitem__\n",
      "    return self.__missing__(key)            # support subclasses that define __missing__\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\collections\\__init__.py\", line 1006, in __missing__\n",
      "    raise KeyError(key)\n",
      "KeyError: 'sess'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 242, in resolve\n",
      "    return self.temps[key]\n",
      "           ~~~~~~~~~~^^^^^\n",
      "KeyError: 'sess'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandasgui\\store.py\", line 621, in apply_filters\n",
      "    df = df.query(filt.expr, engine='python')\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4811, in query\n",
      "    res = self.eval(expr, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4937, in eval\n",
      "    return _eval(expr, inplace=inplace, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\eval.py\", line 336, in eval\n",
      "    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 809, in __init__\n",
      "    self.terms = self.parse()\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 828, in parse\n",
      "    return self._visitor.visit(self.expr)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 418, in visit_Module\n",
      "    return self.visit(expr, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 421, in visit_Expr\n",
      "    return self.visit(node.value, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 545, in visit_Name\n",
      "    return self.term_type(node.id, self.env, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\ops.py\", line 91, in __init__\n",
      "    self._value = self._resolve_name()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\ops.py\", line 115, in _resolve_name\n",
      "    res = self.env.resolve(local_name, is_local=is_local)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 244, in resolve\n",
      "    raise UndefinedVariableError(key, is_local) from err\n",
      "pandas.errors.UndefinedVariableError: name 'sess' is not defined\n",
      "PandasGUI ERROR — pandasgui.store — ('unterminated string literal (detected at line 1)', (1, 6))\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandasgui\\store.py\", line 621, in apply_filters\n",
      "    df = df.query(filt.expr, engine='python')\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4811, in query\n",
      "    res = self.eval(expr, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4937, in eval\n",
      "    return _eval(expr, inplace=inplace, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\eval.py\", line 336, in eval\n",
      "    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 809, in __init__\n",
      "    self.terms = self.parse()\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 828, in parse\n",
      "    return self._visitor.visit(self.expr)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 402, in visit\n",
      "    clean = self.preparser(node)\n",
      "            ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 166, in _preparse\n",
      "    return tokenize.untokenize(f(x) for x in tokenize_string(source))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\tokenize.py\", line 296, in untokenize\n",
      "    out = ut.untokenize(iterable)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\tokenize.py\", line 194, in untokenize\n",
      "    self.compat(t, it)\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\tokenize.py\", line 239, in compat\n",
      "    for tok in _itertools.chain([token], iterable):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 166, in <genexpr>\n",
      "    return tokenize.untokenize(f(x) for x in tokenize_string(source))\n",
      "                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\parsing.py\", line 189, in tokenize_string\n",
      "    for toknum, tokval, start, _, _ in token_generator:\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\tokenize.py\", line 543, in _generate_tokens_from_c_tokenizer\n",
      "    raise TokenError(msg, (e.lineno, e.offset)) from None\n",
      "tokenize.TokenError: ('unterminated string literal (detected at line 1)', (1, 6))\n",
      "PandasGUI ERROR — pandasgui.store — name 'ion' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 231, in resolve\n",
      "    return self.resolvers[key]\n",
      "           ~~~~~~~~~~~~~~^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\collections\\__init__.py\", line 1014, in __getitem__\n",
      "    return self.__missing__(key)            # support subclasses that define __missing__\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\collections\\__init__.py\", line 1006, in __missing__\n",
      "    raise KeyError(key)\n",
      "KeyError: 'ion'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 242, in resolve\n",
      "    return self.temps[key]\n",
      "           ~~~~~~~~~~^^^^^\n",
      "KeyError: 'ion'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandasgui\\store.py\", line 621, in apply_filters\n",
      "    df = df.query(filt.expr, engine='python')\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4811, in query\n",
      "    res = self.eval(expr, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4937, in eval\n",
      "    return _eval(expr, inplace=inplace, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\eval.py\", line 336, in eval\n",
      "    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 809, in __init__\n",
      "    self.terms = self.parse()\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 828, in parse\n",
      "    return self._visitor.visit(self.expr)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 418, in visit_Module\n",
      "    return self.visit(expr, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 421, in visit_Expr\n",
      "    return self.visit(node.value, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 719, in visit_Compare\n",
      "    return self.visit(binop)\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 532, in visit_BinOp\n",
      "    op, op_class, left, right = self._maybe_transform_eq_ne(node)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 452, in _maybe_transform_eq_ne\n",
      "    left = self.visit(node.left, side=\"left\")\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 545, in visit_Name\n",
      "    return self.term_type(node.id, self.env, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\ops.py\", line 91, in __init__\n",
      "    self._value = self._resolve_name()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\ops.py\", line 115, in _resolve_name\n",
      "    res = self.env.resolve(local_name, is_local=is_local)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 244, in resolve\n",
      "    raise UndefinedVariableError(key, is_local) from err\n",
      "pandas.errors.UndefinedVariableError: name 'ion' is not defined\n",
      "PandasGUI ERROR — pandasgui.store — name 'ion' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 231, in resolve\n",
      "    return self.resolvers[key]\n",
      "           ~~~~~~~~~~~~~~^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\collections\\__init__.py\", line 1014, in __getitem__\n",
      "    return self.__missing__(key)            # support subclasses that define __missing__\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\collections\\__init__.py\", line 1006, in __missing__\n",
      "    raise KeyError(key)\n",
      "KeyError: 'ion'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 242, in resolve\n",
      "    return self.temps[key]\n",
      "           ~~~~~~~~~~^^^^^\n",
      "KeyError: 'ion'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandasgui\\store.py\", line 621, in apply_filters\n",
      "    df = df.query(filt.expr, engine='python')\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4811, in query\n",
      "    res = self.eval(expr, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4937, in eval\n",
      "    return _eval(expr, inplace=inplace, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\eval.py\", line 336, in eval\n",
      "    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 809, in __init__\n",
      "    self.terms = self.parse()\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 828, in parse\n",
      "    return self._visitor.visit(self.expr)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 418, in visit_Module\n",
      "    return self.visit(expr, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 421, in visit_Expr\n",
      "    return self.visit(node.value, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 719, in visit_Compare\n",
      "    return self.visit(binop)\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 532, in visit_BinOp\n",
      "    op, op_class, left, right = self._maybe_transform_eq_ne(node)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 452, in _maybe_transform_eq_ne\n",
      "    left = self.visit(node.left, side=\"left\")\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 545, in visit_Name\n",
      "    return self.term_type(node.id, self.env, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\ops.py\", line 91, in __init__\n",
      "    self._value = self._resolve_name()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\ops.py\", line 115, in _resolve_name\n",
      "    res = self.env.resolve(local_name, is_local=is_local)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 244, in resolve\n",
      "    raise UndefinedVariableError(key, is_local) from err\n",
      "pandas.errors.UndefinedVariableError: name 'ion' is not defined\n",
      "PandasGUI ERROR — pandasgui.store — name 'ion' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 231, in resolve\n",
      "    return self.resolvers[key]\n",
      "           ~~~~~~~~~~~~~~^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\collections\\__init__.py\", line 1014, in __getitem__\n",
      "    return self.__missing__(key)            # support subclasses that define __missing__\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\collections\\__init__.py\", line 1006, in __missing__\n",
      "    raise KeyError(key)\n",
      "KeyError: 'ion'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 242, in resolve\n",
      "    return self.temps[key]\n",
      "           ~~~~~~~~~~^^^^^\n",
      "KeyError: 'ion'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandasgui\\store.py\", line 621, in apply_filters\n",
      "    df = df.query(filt.expr, engine='python')\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4811, in query\n",
      "    res = self.eval(expr, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4937, in eval\n",
      "    return _eval(expr, inplace=inplace, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\eval.py\", line 336, in eval\n",
      "    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 809, in __init__\n",
      "    self.terms = self.parse()\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 828, in parse\n",
      "    return self._visitor.visit(self.expr)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 418, in visit_Module\n",
      "    return self.visit(expr, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 421, in visit_Expr\n",
      "    return self.visit(node.value, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 719, in visit_Compare\n",
      "    return self.visit(binop)\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 532, in visit_BinOp\n",
      "    op, op_class, left, right = self._maybe_transform_eq_ne(node)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 452, in _maybe_transform_eq_ne\n",
      "    left = self.visit(node.left, side=\"left\")\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 545, in visit_Name\n",
      "    return self.term_type(node.id, self.env, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\ops.py\", line 91, in __init__\n",
      "    self._value = self._resolve_name()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\ops.py\", line 115, in _resolve_name\n",
      "    res = self.env.resolve(local_name, is_local=is_local)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 244, in resolve\n",
      "    raise UndefinedVariableError(key, is_local) from err\n",
      "pandas.errors.UndefinedVariableError: name 'ion' is not defined\n",
      "PandasGUI ERROR — pandasgui.store — name 'sessionion' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 231, in resolve\n",
      "    return self.resolvers[key]\n",
      "           ~~~~~~~~~~~~~~^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\collections\\__init__.py\", line 1014, in __getitem__\n",
      "    return self.__missing__(key)            # support subclasses that define __missing__\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\collections\\__init__.py\", line 1006, in __missing__\n",
      "    raise KeyError(key)\n",
      "KeyError: 'sessionion'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 242, in resolve\n",
      "    return self.temps[key]\n",
      "           ~~~~~~~~~~^^^^^\n",
      "KeyError: 'sessionion'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandasgui\\store.py\", line 621, in apply_filters\n",
      "    df = df.query(filt.expr, engine='python')\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4811, in query\n",
      "    res = self.eval(expr, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\frame.py\", line 4937, in eval\n",
      "    return _eval(expr, inplace=inplace, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\eval.py\", line 336, in eval\n",
      "    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 809, in __init__\n",
      "    self.terms = self.parse()\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 828, in parse\n",
      "    return self._visitor.visit(self.expr)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 418, in visit_Module\n",
      "    return self.visit(expr, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 421, in visit_Expr\n",
      "    return self.visit(node.value, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 719, in visit_Compare\n",
      "    return self.visit(binop)\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 532, in visit_BinOp\n",
      "    op, op_class, left, right = self._maybe_transform_eq_ne(node)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 452, in _maybe_transform_eq_ne\n",
      "    left = self.visit(node.left, side=\"left\")\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 412, in visit\n",
      "    return visitor(node, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\expr.py\", line 545, in visit_Name\n",
      "    return self.term_type(node.id, self.env, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\ops.py\", line 91, in __init__\n",
      "    self._value = self._resolve_name()\n",
      "                  ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\ops.py\", line 115, in _resolve_name\n",
      "    res = self.env.resolve(local_name, is_local=is_local)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\pandas\\core\\computation\\scope.py\", line 244, in resolve\n",
      "    raise UndefinedVariableError(key, is_local) from err\n",
      "pandas.errors.UndefinedVariableError: name 'sessionion' is not defined\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "c:\\Users\\arturoV\\AppData\\Local\\miniconda3\\envs\\visualization\\Lib\\site-packages\\ipykernel\\eventloops.py:128: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# import pandas as pd\n",
    "from pandasgui import show\n",
    "import pandas as pd\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "raw_matrix_df_thr_0_1=pd.read_excel('analysed/tables/raw_matrix_df_thr_0.1.xlsx')\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "capture_df=pd.read_excel('capture_df.xlsx')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "PandasGUI INFO — pandasgui.gui — Opening PandasGUI\n",
      "C:\\Users\\arturoV\\AppData\\Local\\Temp\\ipykernel_34664\\383630489.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  show(raw_matrix_df_thr_0_1,capture_df)\n",
      "C:\\Users\\arturoV\\AppData\\Local\\Temp\\ipykernel_34664\\383630489.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  show(raw_matrix_df_thr_0_1,capture_df)\n",
      "C:\\Users\\arturoV\\AppData\\Local\\Temp\\ipykernel_34664\\383630489.py:1: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "C:\\Users\\arturoV\\AppData\\Local\\Temp\\ipykernel_34664\\383630489.py:1: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "C:\\Users\\arturoV\\AppData\\Local\\Temp\\ipykernel_34664\\383630489.py:1: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "C:\\Users\\arturoV\\AppData\\Local\\Temp\\ipykernel_34664\\383630489.py:1: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "C:\\Users\\arturoV\\AppData\\Local\\Temp\\ipykernel_34664\\383630489.py:1: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "C:\\Users\\arturoV\\AppData\\Local\\Temp\\ipykernel_34664\\383630489.py:1: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "C:\\Users\\arturoV\\AppData\\Local\\Temp\\ipykernel_34664\\383630489.py:1: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "C:\\Users\\arturoV\\AppData\\Local\\Temp\\ipykernel_34664\\383630489.py:1: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "C:\\Users\\arturoV\\AppData\\Local\\Temp\\ipykernel_34664\\383630489.py:1: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n",
      "C:\\Users\\arturoV\\AppData\\Local\\Temp\\ipykernel_34664\\383630489.py:1: FutureWarning:\n",
      "\n",
      "Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<pandasgui.gui.PandasGui at 0x1c99b536180>"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "show(raw_matrix_df_thr_0_1,capture_df)\n",
    "# show(raw_matrix_df_thr_0)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "analysis",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
